# This file was generated by GoReleaser. DO NOT EDIT.
class Gtag < Formula
  desc "Help you to get golang struct's tags elegantly."
  homepage "https://github.com/wolfogre/gtag"
  version "0.7.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wolfogre/gtag/releases/download/v0.7.2/gtag_0.7.2_darwin_amd64.tar.gz"
    sha256 "1fbcc26cfb7a644d52c3e79e811f7ad4e56e43b47e45de84e7672388aec78a22"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/wolfogre/gtag/releases/download/v0.7.2/gtag_0.7.2_linux_amd64.tar.gz"
      sha256 "6700277be4088c7711ef6f3d87670347f510bb8dcddf094489d463159a92d1bf"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wolfogre/gtag/releases/download/v0.7.2/gtag_0.7.2_linux_arm64.tar.gz"
        sha256 "79edac148e5f01570d3e0eb53a7f68563ae8671f13dbbd4beacd299de7576d8d"
      else
        url "https://github.com/wolfogre/gtag/releases/download/v0.7.2/gtag_0.7.2_linux_armv6.tar.gz"
        sha256 "8012c213048b528f4d3bc18271ff0902874d650e41d615890c1a9ca7a285d358"
      end
    end
  end

  def install
    bin.install "gtag"
  end

  test do
    system "#{bin}/gtag -version"
  end
end
