# This file was generated by GoReleaser. DO NOT EDIT.
class Gtag < Formula
  desc "Help you to get golang struct's tags elegantly."
  homepage "https://github.com/wolfogre/gtag"
  version "0.8.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wolfogre/gtag/releases/download/v0.8.0/gtag_0.8.0_darwin_amd64.tar.gz"
    sha256 "48b9f2f0431a9f12fa19d6e932daece6209a3eb57e8bc87d36c0cbb6c69dde71"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/wolfogre/gtag/releases/download/v0.8.0/gtag_0.8.0_linux_amd64.tar.gz"
      sha256 "e1268d35c5793819f3e447367e2250d05109938ff67409ccf73b2fc244c2dfc8"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wolfogre/gtag/releases/download/v0.8.0/gtag_0.8.0_linux_arm64.tar.gz"
        sha256 "b631fd73e3383aaf1c67fa4193c9ac27222c24676f72318a5bf88ab45f072bcb"
      else
        url "https://github.com/wolfogre/gtag/releases/download/v0.8.0/gtag_0.8.0_linux_armv6.tar.gz"
        sha256 "4ad61a02c8b60c2480a5f875a8e2c05f085285f2e53c9b5932bd04aae4b0b925"
      end
    end
  end

  def install
    bin.install "gtag"
  end

  test do
    system "#{bin}/gtag -version"
  end
end
