# This file was generated by GoReleaser. DO NOT EDIT.
class Modimports < Formula
  desc "Wrapper for goimports."
  homepage "https://github.com/wolfogre/modimports"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wolfogre/modimports/releases/download/v0.1.2/modimports_0.1.2_darwin_amd64.tar.gz"
    sha256 "c20c47472408f09af530f56c2541af20c2c55b0f00eb3fe75ad61082382ad62c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/wolfogre/modimports/releases/download/v0.1.2/modimports_0.1.2_linux_amd64.tar.gz"
      sha256 "30d62cd6b9cd9f9e3953b06baf14ea6868e3eac62df84e5780afc2c3afd31d22"
    end
  end
  
  depends_on "wolfogre/tap/gotools"

  def install
    bin.install "modimports"
  end

  test do
    system "#{bin}/modimports /dev/null"
  end
end
